engineImportTXD(engineLoadTXD("files/atm.txd"), 2942)
engineReplaceModel(engineLoadDFF("files/atm.dff", 2942), 2942)
engineReplaceCOL(engineLoadCOL("files/atm.col"), 2942)
engineImportTXD(engineLoadTXD("files/marysia.txd"), 325)
engineReplaceModel(engineLoadDFF("files/marysia.dff", 325), 325)
engineImportTXD(engineLoadTXD("files/trojkat.txd"), 1425)
engineReplaceModel(engineLoadDFF("files/trojkat.dff", 1425), 1425)
engineReplaceCOL(engineLoadCOL("files/trojkat.col"), 1425)
engineImportTXD(engineLoadTXD("files/defibrylator.txd"), 8318)
engineReplaceModel(engineLoadDFF("files/defibrylator.dff", 8318), 8318)
engineReplaceCOL(engineLoadCOL("files/defibrylator.col"), 8318)
engineImportTXD(engineLoadTXD("files/wentylator.txd"), 8316)
engineReplaceModel(engineLoadDFF("files/wentylator.dff", 8316), 8316)
engineReplaceCOL(engineLoadCOL("files/wentylator.col"), 8316)
engineImportTXD(engineLoadTXD("files/nosze.txd"), 1997)
engineReplaceModel(engineLoadDFF("files/nosze.dff", 1997), 1997)
engineReplaceCOL(engineLoadCOL("files/nosze.col"), 1997)
engineImportTXD(engineLoadTXD("files/taxi.txd"), 1939)
engineReplaceModel(engineLoadDFF("files/taxi.dff", 1939), 1939)
engineImportTXD(engineLoadTXD("files/weaponFuel.txd"), 10012)
engineReplaceModel(engineLoadDFF("files/weaponFuel.dff", 10012), 10012)
engineImportTXD(engineLoadTXD("files/bucket.txd"), 2713)
engineReplaceModel(engineLoadDFF("files/bucket.dff", 2713), 2713)
engineImportTXD(engineLoadTXD("files/plama.txd"), 902)
engineReplaceModel(engineLoadDFF("files/plama.dff", 902), 902)
engineImportTXD(engineLoadTXD("files/kilof.txd"), 322)
engineReplaceModel(engineLoadDFF("files/kilof.dff"), 322, true)
getResourceName(getThisResource(), true, 69554900)
return
